mysql:
  username: ${MYSQL_USERNAME:root}
  password: ${MYSQL_ROOT_PASSWORD:root}
  schema: bootdb
  host: ${MYSQL_HOST:mysql}
  port: ${MYSQL_PORT:3306}

server:
  host: ${SERVER_HOST:localhost}
  port: ${SERVER_PORT:8081}
  undertow:
    threads:
      worker: 10
      io: 2

external:
  validation:
    base-url: ${VALIDATION_SERVICE_URL:http://localhost:8080}
  registration:
    base-url: ${REGISTRATION_SERVICE_URL:http://localhost:8080}