mysql:
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_ROOT_PASSWORD}
  schema: bootdb
  host: ${MYSQL_HOST}
  port: ${MYSQL_PORT:3306}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none