mysql:
  username: root
  password: root
  schema: bootdb
  url: localhost:3306

server:
  port: 8081
  undertow:
    threads:
      worker: 10
      io: 2

external:
  validation:
    base-url: ${VALIDATION_SERVICE_URL:http://localhost:8080}